### ISSUE TITLE
Add ability to create AWS load balancer with internal scheme.

### ISSUE THREAD

**Issue by b0nete** [KongZ/charts#12]
**Describe the problem**
This chart create a AWS load balancer with scheme "internet-facing", please allow create load balancer with scheme internal. 

**What you expected to happen**:
Plase add some field to values.yaml and allow or deny create internal load balancer.

Maybe something like that.
`  input:
    tcp:
      service:
        type: LoadBalancer
        **scheme: internal**
        loadBalancerIP:
      ports:
        - name: gelf
          port: 12222`

and add to service-tcp.yaml this annotations

`annotations:
  service.beta.kubernetes.io/aws-load-balancer-internal: "true"`

**Comment by KongZ** [comment]
You can add annotation to tcp service by `.Values.graylog.input.tcp.service.annotations`
e.g.
```
graylog:
  input:
    tcp:
      service:
        type: LoadBalancer
        annotations:
         service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
         service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
         service.beta.kubernetes.io/aws-load-balancer-internal: "true"
     ports:
       - name: gelf
          port: 12222
```
