### ISSUE TITLE
Troubles installing chart with ingress

### ISSUE THREAD

**Issue by maranmaran** [KongZ/charts#14]
Hello everyone I'm trying to install graylog chart with ingress enabled and I'm running into:

`Error: Ingress.extensions "graylog-web" is invalid: spec: Invalid value: []networking.IngressRule(nil): either 'backend' or 'rules' must be specified`

My values file only contains:

```
graylog:
  ingress:
    enabled: true
```

I believe it's a minor thing but not sure what I'm missing.

EDIT:

Sorry I must've misunderstood that other things default to something 

```
  ingress:
    enabled: true
    annotations: {}
    labels: {}
    hosts:
      - myhost.com
    extraPaths: 
      - path: /graylog
        backend:
          serviceName: graylog-web
          servicePort: 9000
    tls: []
```
