### ISSUE TITLE
Configuration for GELF HTTP input

### ISSUE THREAD

**Issue by CoMaDaniel** [KongZ/charts#17]
Hello.

I apologize in advance if this is a noob question, I'm fairly new at this.

Long story short, I have managed to deploy Graylog in a self managed K8s cluster, everything works pretty well.
I am facing an issue right now: as per requirements, I need to send logs via HTTP from outside the cluster on port 443.
My idea was using an Ingress that will route the incoming traffic from myIngressHost port 443 to my GELF HTTP on port 12201, let's say.
I tried configuring the Ingress to use a secret and set the endpoint to myGraylogMasterService port 12201. I have started the input in the UI. Alas, I get Connection Refused.
I looked into configuring the input via the helm chart, as it is required, but I only find examples of TCP or UDP inputs. Using those toghether with ingress does not seem (easily) possible.
How should the helm chart be deployed so I can use GELF HTTP input?
Thanks for the responses and sorry again for the noob question.

**Comment by KongZ** [comment]
The HTTP uses TCP to transmit data. So you can GELF HTTP Input on `input.tcp`.
For example:

```
  input:
    tcp:
      service:
        type: LoadBalancer
        externalTrafficPolicy: Local
      ports:
        - name: gelf1
          port: 12221
```

This will create another Load Balancer with port `12221` and you can use this Load Balancer for your GELF HTTP input
