### ISSUE TITLE
Ingress is not working

### ISSUE THREAD

**Issue by drkhosla** [KongZ/charts#35]
**Describe the bug**

Unable to install graylog with enabling ingress

**Version of Helm and Kubernetes**:

Helm Version:

```console
$ helm version
version.BuildInfo{Version:"v3.3.4", GitCommit:"a61ce5633af99708171414353ed49547cf05013d", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:10:43Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:41:49Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
1.7.8

**What happened**:

$helm install --debug --dry-run -n graylog graylog -f values.yaml .

install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /root/graylog

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0]): invalid type for io.k8s.api.networking.v1beta1.HTTPIngressPath: got "string", expected "map"
helm.go:94: [debug] error validating "": error validating data: ValidationError(Ingress.spec.rules[0].http.paths[0]): invalid type for io.k8s.api.networking.v1beta1.HTTPIngressPath: got "string", expected "map"
helm.sh/helm/v3/pkg/kube.scrubValidationError
	/home/circleci/helm.sh/helm/pkg/kube/client.go:566
helm.sh/helm/v3/pkg/kube.(*Client).Build
	/home/circleci/helm.sh/helm/pkg/kube/client.go:159
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:255
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373
unable to build kubernetes objects from release manifest
helm.sh/helm/v3/pkg/action.(*Install).Run
	/home/circleci/helm.sh/helm/pkg/action/install.go:257
main.runInstall
	/home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newInstallCmd.func2
	/home/circleci/helm.sh/helm/cmd/helm/install.go:120
github.com/spf13/cobra.(*Command).execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842
github.com/spf13/cobra.(*Command).ExecuteC
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950
github.com/spf13/cobra.(*Command).Execute
	/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main
	/home/circleci/helm.sh/helm/cmd/helm/helm.go:93
runtime.main
	/usr/local/go/src/runtime/proc.go:203
runtime.goexit
	/usr/local/go/src/runtime/asm_amd64.s:1373

**What you expected to happen**:
Should install graylog with proper externalUri

**How to reproduce it** (as minimally and precisely as possible):
Change the value of ingress.enabled, hosts and extraPath

values.yaml (only put values which differ from the defaults)
**ingress:**
    **enabled: true**
    **hosts: [graylog-0]**
    **extraPaths: [/graylog]**
```
graylog.ingress.enable true
graylog.ingress.hosts [graylog-0]
graylog.ingress.extraPath[/graylog]
```
```
helm install --debug --dry-run -n graylog graylog -f values.yaml .
```

**Anything else we need to know**:
If I create graylog Ingress independent, it does not create proper externalUri web interface. I think to get proper externalUri, ingress should be created with graylog helm chart.

**Comment by KongZ** [comment]
Extra path requires valid `path`. Your value is not valid. Check out Ingress document.
https://kubernetes.io/docs/concepts/services-networking/ingress/

And Graylog requires adding Graylog url in Graylog configuration file so you can't manual create ingress without modifying Graylog configuration.

btw. `graylog.ingress.hosts=[graylog-0]` looks invalid too. It should be FQDN

**Comment by KongZ** [comment]
Check out `extraPaths` sample here

https://github.com/KongZ/charts/blob/main/charts/graylog/values.yaml#L239-L243

**Comment by drkhosla** [comment]
When I add any thing to externalPath, it generate erroneous yaml from ingress template.  I just add external uri in values.yaml and enable cors (domain name is masked with xxxx).

```
externalUri: "graylog.xxxxxxxx.net/log"
```
```
  config: |
      http_enable_cors = true
```
and disable ingress.

```
ingress: 
   enabled: false
```
and added new ingress graylog-web independently

```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
  labels:
    helm.sh/chart: graylog-1.7.8
    app.kubernetes.io/name: graylog
    app.kubernetes.io/instance: "graylog"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "4.0.2"
    app.kubernetes.io/component: "web"
  name: graylog-web
  namespace: graylog
spec:
  rules:
    - host: graylog.xxxxxx.net
      http:
        paths:
          - path: /log
            pathType: Prefix
            backend:
               serviceName: graylog-web
               servicePort: graylog
```
Apart from master there are 4 nodes and we are able to run three replica of each services.
```
graylog-0                                       1/1     Running   0          94m
graylog-1                                       1/1     Running   0          93m
graylog-2                                       1/1     Running   0          92m
graylog-elasticsearch-client-5fb4bf5d7d-dptbt   1/1     Running   0          94m
graylog-elasticsearch-client-5fb4bf5d7d-ldg5w   1/1     Running   0          94m
graylog-elasticsearch-client-5fb4bf5d7d-vmdcb   1/1     Running   0          94m
graylog-elasticsearch-data-0                    1/1     Running   0          94m
graylog-elasticsearch-data-1                    1/1     Running   0          93m
graylog-elasticsearch-data-2                    1/1     Running   0          93m
graylog-elasticsearch-master-0                  1/1     Running   0          94m
graylog-elasticsearch-master-1                  1/1     Running   0          93m
graylog-elasticsearch-master-2                  1/1     Running   0          93m
graylog-mongodb-0                               1/1     Running   0          94m
graylog-mongodb-1                               1/1     Running   0          94m
graylog-mongodb-2                               1/1     Running   0          94m
graylog-mongodb-arbiter-0                       1/1     Running   0          94m
```
graylog.conf is
```
node_id_file = /usr/share/graylog/data/journal/node-id
root_username = admin
root_email = 
root_timezone = UTC
http_bind_address = 0.0.0.0:9000
http_external_uri = http://graylog.xxxxxx.net/log/
elasticsearch_hosts = http://graylog-elasticsearch-client.graylog.svc.cluster.local:9200
allow_leading_wildcard_searches = false
allow_highlighting = false
output_batch_size = 500
output_flush_interval = 1
output_fault_count_threshold = 5
output_fault_penalty_seconds = 30
processbuffer_processors = 5
outputbuffer_processors = 3
processor_wait_strategy = blocking
ring_size = 65536
inputbuffer_ring_size = 65536
inputbuffer_processors = 2
inputbuffer_wait_strategy = blocking
message_journal_enabled = true
# Do not change `message_journal_dir` location
message_journal_dir = /usr/share/graylog/data/journal
lb_recognition_period_seconds = 3
# Use a replica set instead of a single host
mongodb_uri = mongodb://graylog-mongodb-headless.graylog.svc.cluster.local:27017/graylog?replicaSet=rs0
mongodb_max_connections = 1000
mongodb_threads_allowed_to_block_multiplier = 5
# Email transport
transport_email_enabled = false
transport_email_hostname = 
transport_email_port = 2587
transport_email_use_auth = true
transport_email_use_tls = true
transport_email_use_ssl = false
transport_email_auth_username = 
transport_email_auth_password = 
transport_email_subject_prefix = [graylog]
transport_email_from_email = 
transport_email_web_interface_url = http://graylog.xxxxxx.net/log
content_packs_dir = /usr/share/graylog/data/contentpacks
content_packs_auto_load = grok-patterns.json
proxied_requests_thread_pool_size = 32
http_enable_cors = true

```
It seem everything is working fine but when I try to access web interface http://graylog.xxxxx.net/log get blank page with source..
```

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="robots" content="noindex, nofollow">
    <meta charset="UTF-8">
    <title>Graylog Web Interface</title>
    <link rel="shortcut icon" href="http://graylog.xxxxxxx.net/log/assets/favicon.png">
    
  </head>
  <body>
    <script src="http://graylog.xxxxxxx.net/log/config.js"></script>
    
    <script src="http://graylog.xxxxxxx.net/log/assets/vendor.594b2a39cb22b445205e.js"></script>
    
    <script src="http://graylog.xxxxxxx.net/log/assets/polyfill.8b3b9f6d523cfce42b22.js"></script>
    
    <script src="http://graylog.xxxxxxx.net/log/assets/builtins.8b3b9f6d523cfce42b22.js"></script>
    
    <script src="http://graylog.xxxxxxx.net/log/assets/plugin/org.graylog.plugins.threatintel.ThreatIntelPlugin/plugin.org.graylog.plugins.threatintel.ThreatIntelPlugin.460311475d1a8f9bdd10.js"></script>
    
    <script src="http://graylog.xxxxxxx.net/log/assets/plugin/org.graylog.plugins.collector.CollectorPlugin/plugin.org.graylog.plugins.collector.CollectorPlugin.297c17a610dc2eed4ce7.js"></script>
    
    <script src="http://graylog.xxxxxxx.net/log/assets/plugin/org.graylog.aws.AWSPlugin/plugin.org.graylog.aws.AWSPlugin.56318a65c00e53d5f929.js"></script>
    
    <script src="http://graylog.xxxxxxx.net/log/assets/app.8b3b9f6d523cfce42b22.js"></script>
    
  </body>
</html>
```
I don't know how to solve this problem. Am I missing something..

**Comment by drkhosla** [comment]
I made few changes in values.yaml and ingress file and successfully able to run web interface. Apart from master, we have 4 nodes (domain name is masked with xxxxxx)

Changes in values.yaml
```
graylog.replicas: 3
externalUri: "graylog.xxxxxx.net"
ingress.enable: false
config: |
      http_enable_cors = true
      http_publish_uri = http://graylog.xxxxx.net
      web_enable = true
elasticsearch:
  image:
    repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
    tag: "6.8.13"
  client:
    replicas: 3
  master:
    replicas: 3
  data:
    replicas: 3
  cluster:
    env:
      MINIMUM_MASTER_NODES: 1
    xpackEnable: false

mongodb:
  architecture: "replicaset"
  useStatefulSet: true
  replicaCount: 3
  auth:
    enabled: false
```
As I disabled ingress in values.yaml. I have to create ingress for web interface. The working ingress yaml file is..
```
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Request-Id: $req_id";
      more_set_headers "X-Graylog-Server-URL http://graylog.xxxxxx.net";
    kubernetes.io/ingress.class: "nginx"
  labels:
    helm.sh/chart: graylog-1.7.8
    app.kubernetes.io/name: graylog
    app.kubernetes.io/instance: "graylog"
    app.kubernetes.io/managed-by: "Helm"
    app.kubernetes.io/version: "4.0.2"
    app.kubernetes.io/component: "web"
  name: graylog-web
  namespace: graylog
spec:
  rules:
    - host: graylog.ankhnet.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
               serviceName: graylog-web
               servicePort: graylog
```
As we already running ingress-nginx in kubernetes cluster, just adding few annotation in ingress file works like magic.

Hope it will solve many people problems running graylog multinode cluster.
