### ISSUE TITLE
Input configuration 

### ISSUE THREAD

**Issue by JaronPiet** [KongZ/charts#41]
I am try using the graylog helm chart to get an instance run in aks. I am stuck while defining a simple input. The deployment works without errors but when i check the inputs on the graylog UI there is no input.
The input should only reach/accessable from services inside the cluster.

Thats my input definition:

```
….
  input:
    tcp:
      service:
        name: mms-input
        type: ClusterIP
      ports:
        - name: gelfhttp
          port: 12201
….
```

Is there anything i forgot or wrong?

**Comment by KongZ** [comment]
The input on Graylog UI needs manually created by yourself. Cause it is not creatable from helm chart. The helm chart will only create services.
And for EKS, you may need to put AWS annotations on too e.g.
```
graylog
   input:
      tcp:
         service:
            annotations: 
               service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip
```
