### ISSUE TITLE
Graylog cluster launches all nodes as master or several nodes as master

### ISSUE THREAD

**Issue by vodwood** [KongZ/charts#44]
**Describe the bug**
While performing upgrades of the helm chart/graylog version, multiple masters come up instead of one.

**Version of Helm and Kubernetes**:

Helm Version: 

```console
$ helm version
version.BuildInfo{Version:"v3.3.3", GitCommit:"55e3ca022e40fe200fbc855938995f40b2a68ce0", GitTreeState:"clean", GoVersion:"go1.14.9"}
```

Kubernetes Version:

```console
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18+", GitVersion:"v1.18.9-eks-d1db3c", GitCommit:"d1db3c46e55f95d6a7d3e5578689371318f95ff9", GitTreeState:"clean", BuildDate:"2020-10-20T22:18:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Which version of the chart**:
graylog-1.7.10

**What happened**:
After installing a multiple node cluster, all Graylog nodes come up as masters, with a warning message displayed.

**What you expected to happen**:
Init script to initialize the first node as master, and all consequent nodes as worker.

**How to reproduce it** (as minimally and precisely as possible):

```
image:
    repository: "graylog/graylog:4.0.6"
persistence:
    enabled: true
    accessMode: ReadWriteOnce
    size: "50Gi"
    storageClass: "ebs-sc"
```

```
helm -n graylog upgrade --install -f values.yml graylog kongz/graylog --version 1.7.10
```

**Anything else we need to know**:
Roll back version 1.7.5 does bring up one master and N workers correctly.

**Comment by mchiappini** [comment]
I can confirm this is happening to me too. Rolling back to `1.7.5` solves the issue

**Comment by pparthesh** [comment]
Not able to create cluster using 3 pods. 

chart version: 1.8.7

pod-0
```
The connection to the server 100.64.0.1:443 was refused - did you specify the right host or port?
The connection to the server 100.64.0.1:443 was refused - did you specify the right host or port?
Current master is
Self IP is
Launching graylog-testonly-0 as master
The connection to the server 100.64.0.1:443 was refused - did you specify the right host or port?
Starting graylog
Graylog Home /usr/share/graylog
```

pod-1
```
The connection to the server 100.64.0.1:443 was refused - did you specify the right host or port?
The connection to the server 100.64.0.1:443 was refused - did you specify the right host or port?
Current master is
Self IP is
Launching graylog-testonly-1 as master
The connection to the server 100.64.0.1:443 was refused - did you specify the right host or port?
Starting graylog
Graylog Home /usr/share/graylog
```

pod-2
```
The connection to the server 100.64.0.1:443 was refused - did you specify the right host or port?
The connection to the server 100.64.0.1:443 was refused - did you specify the right host or port?
Current master is
Self IP is
Launching graylog-testonly-1 as master
The connection to the server 100.64.0.1:443 was refused - did you specify the right host or port?
Starting graylog
Graylog Home /usr/share/graylog
```

**Comment by KongZ** [comment]
@pparthesh  Connecting to port `443` is not a normal configuration. Can you post a content of your value file?

**Comment by pparthesh** [comment]
values.yaml
```
tags:
  install-elasticsearch: false
  install-mongodb: true

graylog:
  image:
    repository: "graylog/graylog:4.1.3-1"

  replicas: 3

  persistence:
    enabled: true
    size: "20Gi"

  service:
    headless:
      suffix: headless

  input:
    tcp:
      service:
        name: graylog-input-tcp-service
        type: ClusterIP
      ports:
        - name: syslog-tcp
          port: 12211
        - name: gelf-tcp
          port: 12212
    udp:
      service:
        name: graylog-input-udp-service
        type: ClusterIP
      ports:
        - name: syslog-udp
          port: 12221
        - name: gelf-udp
          port: 12222

  ingress:
    enabled: true
    hosts:
      - XXXX

  resources:
    limits:
      cpu: "500m"
      memory: "1024Mi"
    requests:
      cpu: "500m"
      memory: "1024Mi"

  rootUsername: "XXXX"
  rootPassword: "XXXX"
  rootEmail: "XXXX"

  elasticsearch:
    version: "7"
    hosts: "XXXX"
    uriSSL: false

mongodb:
  architecture: "replicaset"
  useStatefulSet: true
  replicaCount: 1
  resources:
    limits:
      cpu: 200m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 256Mi
  auth:
    enabled: false
  persistence:
    enabled: true
```
