### ISSUE TITLE
Source IP is logged with internal cluster

### ISSUE THREAD

**Issue by mazmar** [KongZ/charts#68]
This might not be related to graylog at all but I am new to kube so it's still a giant mess for me. 

I have Ingress Controller as loadbalancer with TCP forwarding rule `12222: graylog/graylog-tcp:12222`
I have GrayLog input configured as ClusterIP with port `12222`

it works fine and I am able to connect via telnet. But all logs are showing IP 10.244.2.200 which i assume is some local cluster IP in my kubernetes. 

How should i resolve this? is this issue of the Ingress Controller or is it some config in the graylog service?

Thanks

my helm values:
```
graylog:
  input:
    tcp:
      service:
        type: ClusterIP
      ports:
        - name: rawtcp
          port: 12222
```
